theme: jekyll-theme-hacker
title: CODEX NewsLetter
description: Get updated informations regarding CODEX community, members, their working projects, contributions and achievements. <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSc2s3Q7DE6P4X5BBPwyMJhtmyG2iJTrERmsXtuK413NazzjCw/viewform?embedded=true" width="700" height="520" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>
